---
sudo: required

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro: ubuntu1804
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"




script:

  # Ansible syntax check.
  - 'sudo ansible-playbook /etc/ansible/roles/zoeycluff.betterpress/tests/test.yml --syntax-check'

  # Test role.
  - 'sudo ansible-playbook /etc/ansible/roles/zoeycluff.betterpress/tests/test.yml'


  - 'sudo curl 127.0.0.1'



notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
