---

  - name: check if ondrej PPA exists
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    stat:
      path: /etc/apt/sources.list.d/ppa_ondrej_php_cosmic.list
    register: PPAExists

  - name: allow installation of PHP 7.3 on ubuntu 18.04
    apt_repository:
      repo: 'ppa:ondrej/php'
      state: present
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" and not PPAExists.stat.exists )

  - name: update cache
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt: update_cache=yes
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: update system
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt: upgrade=dist
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
