---

  - name: install packages
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt:
      name:
        - 'nginx'
        - 'php7.4'
        - 'php7.4-mysql'
        - 'php7.4-fpm'
        - 'php7.4-cli'
        - 'php7.4-gd'
        - 'php7.4-json'
        - 'php7.4-mbstring'
        - 'php7.4-readline'
        - 'php7.4-xml'
        - 'php7.4-zip'
        - 'python-pip'
        - 'mysql-server'
        - 'mysql-client'
        - 'libmysqlclient-dev'
        - 'python-mysqldb'
        - 'unzip'
        - 'ufw'

      state: present

    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: install caching
    when: (caching == True and ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt:
      name: memcached
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: install certbot
    when: (leEmail is defined and ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt:
      name: certbot
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
