---
  - name: start NGINX
    service:
      name: nginx
      state: started

  - name: start PHP for Debian based OS
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    service:
      name: php7.3-fpm
      state: started

  - name: start PHP for CentOS based OS
    when: (ansible_distribution == "EL" or ansible_distribution == "Fedora")
    service:
      name: php-fpm
      state: started
