---

  - name: open http on firewall
    when: (ansible_distribution == "EL" or ansible_distribution == "CentOS")
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes


  - name: open https on firewall
    when: (ansible_distribution == "EL" or ansible_distribution == "CentOS" and leEmail is defined)
    firewalld:
      service: https
      permanent: true
      state: enabled
      immediate: yes

  - name: open http on firewall
    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" and ansible_virtualization_type != 'docker')
    ufw:
      port: '80'
      rule: allow
      proto: tcp

  - name: open https on firewall
    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" and leEmail is defined and ansible_virtualization_type != 'docker')
    ufw:
      port: '443'
      rule: allow
      proto: tcp
