---

  - name: open http on firewall
    when: (ansible_distribution == "CentOS" or ansible_distribution == "Fedora" or ansible_distribution == "Red Hat Enterprise Linux")
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: open https on firewall
    when: (ansible_distribution == "CentOS" or ansible_distribution == "Fedora" or ansible_distribution == "Red Hat Enterprise Linux" and leEmail is defined)
    firewalld:
      service: https
      permanent: true
      state: enabled

  - name: open http on firewall
    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")
    ufw:
      port: '80'
      rule: allow
      proto: tcp

  - name: open https on firewall
    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" and leEmail is defined)
    ufw:
      port: '443'
      rule: allow
      proto: tcp
