---
  - hosts: 127.0.0.1
    connection: local
    sudo: required

# tasks file for role-betterpress

  - import_tasks: aptConfig.yaml
  - import_tasks: aptInstall.yaml
  - import_tasks: yumConfig.yaml
  - import_tasks: yumInstall.yaml
  - import_tasks: cloudflare.yaml
  - import_tasks: firewall.yaml
  - import_tasks: mysql.yaml
  - import_tasks: nginx.yaml
  - import_tasks: wordpress.yaml
  - import_tasks: letsencrypt.yaml
  - import_tasks: finalize.yaml
