---
  tasks:
    - name: create www folder
      when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
      file:
        path: "/var/www/{{fullDomain}}"
        state: directory
        mode: 0755
        owner: www-data
        group: www-data

    - name: Create www folder
      when: (ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Fedora")
      file:
        path: "/var/www/{{fulLDomain}}"
        state: directory
        mode: 0755
        owner: apache
        group: apache

    - name: install NGINX config for HTTP only site
      when: (leEmail is not defined)
      template:
        src: ../configs/nginxHTTPconfig.conf.j2
        dest: "/etc/nginx.conf.d/{{fullDomain}}.conf"

    - name: install NGINX config for HTTPS site
      when: (leEmail is defined)
      template:
        src: ../configs/nginxHTTPSconfig.conf.j2
        dest: "/etc/nginx.conf.d/{{fullDomain}}.conf"

    - name: install NGINX config
      copy:
        src: ../configs/nginx.conf
        dest: "/etc/nginx/nginx.conf"
