---
  - name: ensure ssl dhparam exists
    stat:
      path: /etc/nginx/ssl/dhparam.pem
    register: missingdhparam

  - name: ensure ssl folder exists
    file:
      path: /etc/nginx/ssl/
      state: directory
    when: not missingdhparam.stat.exists

  - name: generate dhprams
    shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
    when: not missingdhparam.stat.exists

  - name: make nginx.conf.d folder
    file:
      path: "/etc/nginx/conf.d"
      state: directory


  - name: create www folder
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    file:
      path: "/var/www/{{ fullDomain }}"
      state: directory
      mode: 0755
      owner: www-data
      group: www-data

  - name: Create www folder
    when: (ansible_distribution == "EL" or ansible_distribution == "Fedora" or ansible_distribution == "CentOS")
    file:
      path: "/var/www/{{ fullDomain }}"
      state: directory
      mode: 0755
      owner: apache
      group: apache

  - name: install NGINX config for HTTP only site
    when: (leEmail is not defined)
    template:
      src: nginxHTTPconfig.conf.j2
      dest: "/etc/nginx/conf.d/{{ fullDomain }}.conf"

  - name: install NGINX config for HTTPS site
    when: (leEmail is defined)
    template:
      src: nginxHTTPSconfig.conf.j2
      dest: "/etc/nginx/conf.d/{{ fullDomain }}.conf"

  - name: install NGINX config
    copy:
      src: nginx.conf
      dest: "/etc/nginx/nginx.conf"
