---

  - name: install packages
    when: (ansible_distribution == "EL" or ansible_distribution == "Fedora" or ansible_distribution="CentOS")
    yum: name='{{ item }}' state=present
    with_items:
      - nginx
      - php
      - php-mysqlnd
      - php-fpm
      - php-cli
      - php-gd
      - php-json
      - php-mbstring
      - php-mcrypt
      - php-readline
      - php-xml
      - php-zip
      - python-pip
      - mariadb-server
      - mariadb
      - MySQL-python
      - libselinux-python
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: install caching
    when: (ansible_distribution == "Fedora" or ansible_distribution == "EL")
    yum:
      name: memcached
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: install certbot
    when: (leEmail is defined and ansible_distribution == "Fedora"  or ansible_distribution == "EL")
    yum:
      name: certbot
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
